# Generated by Django 6.0.5 on 2026-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            # Originally django_quill.fields.QuillField (a TextField subclass).
            # The package was removed; 0005 turns the column back into TextField anyway.
            field=models.TextField(),
        ),
    ]
