# Generated by Django 6.0.8 on 2026-10-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_article_is_member_only"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
