# Generated by Django 6.0.8 on 2026-10-01 18:58

from django.db import migrations, models


def fill_body_text(apps, schema_editor):
    from articles.models import html_to_text

    Article = apps.get_model("articles", "Article")
    for article in Article.objects.only("pk", "body").iterator():
        Article.objects.filter(pk=article.pk).update(body_text=html_to_text(article.body))


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_sanitize_existing_bodies"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.RunPython(fill_body_text, migrations.RunPython.noop),
    ]
