# Generated by Django 6.0.8 on 2026-10-01 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystats",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
