# Generated by Django 6.0.8 on 2026-10-01 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_sanitize_existing_bodies"),
        ("stats", "0002_dailystats_local_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstats",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="dailystats",
            options={"ordering": ["-date"], "verbose_name_plural": "daily stats"},
        ),
        migrations.AlterUniqueTogether(
            name="dailystats",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dailystats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("article__isnull", False)),
                fields=("user", "article", "date"),
                name="unique_daily_article_stats",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailystats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("article__isnull", True)),
                fields=("user", "date"),
                name="unique_daily_user_stats",
            ),
        ),
        migrations.DeleteModel(
            name="UserStats",
        ),
    ]
