# Generated by Django 6.0.8 on 2026-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
