# Generated by Django 6.0.8 on 2026-10-01 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_article", "New Article"),
                    ("comment", "Comment"),
                    ("reply", "Reply to Comment"),
                    ("like", "Article Liked"),
                    ("bookmark", "Article Saved"),
                    ("follow", "New Follower"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                fields=("follower", "following"), name="unique_user_following"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("following")), _negated=True),
                name="prevent_self_follow",
            ),
        ),
    ]
